import {node, extend, browser} from '@bhsd/code-standard';

export default extend(
	...node,
	{
		ignores: [
			'bundle/',
			'coverage/',
			'fixtures/',
			'test/*.d.ts',
		],
	},
	{
		files: ['src/**/*.ts'],
		...browser,
	},
	{
		files: [
			'test/**/*.js',
			'test/**/*.ts',
		],
		languageOptions: {
			globals: {
				before: 'readonly',
				beforeEach: 'readonly',
				describe: 'readonly',
				eslint: 'readonly',
				it: 'readonly',
			},
		},
		rules: {
			'func-name-matching': 0,
			'func-names': 0,
			'func-style': 0,
			'logical-assignment-operators': 0,
			'no-empty-function': 0,
			'no-shadow': 0,
			'no-template-curly-in-string': 0,
			'no-underscore-dangle': 0,
			'no-unused-vars': 0,
			'no-useless-concat': 0,
			'no-void': 0,
			'prefer-destructuring': 0,
			'prefer-object-spread': 0,
			radix: 0,
			'@stylistic/array-bracket-newline': 0,
			'@stylistic/function-paren-newline': 0,
			'@stylistic/indent': 0,
			'@stylistic/indent-binary-ops': 0,
			'@stylistic/lines-around-comment': 0,
			'@stylistic/max-len': 0,
			'@stylistic/multiline-comment-style': 0,
			'@stylistic/no-extra-parens': 0,
			'@stylistic/object-curly-spacing': 0,
			'@stylistic/operator-linebreak': 0,
			'@stylistic/quotes': 0,
			'@stylistic/spaced-comment': 0,
			'n/no-extraneous-require': 0,
			'n/no-mixed-requires': 0,
			'unicorn/consistent-conditional-object-spread': 0,
			'unicorn/consistent-function-scoping': 0,
			'unicorn/explicit-length-check': 0,
			'unicorn/new-for-builtins': 0,
			'unicorn/no-array-callback-reference': 0,
			'unicorn/no-array-fill-with-reference-type': 0,
			'unicorn/no-for-each': 0,
			'unicorn/no-array-reduce': 0,
			'unicorn/no-useless-template-literals': 0,
			'unicorn/number-literal-case': 0,
			'unicorn/prefer-spread': 0,
			'unicorn/prefer-string-raw': 0,
			'unicorn/prefer-string-replace-all': 0,
			'regexp/no-super-linear-move': 0,
		},
		settings: {
			node: {
				version: '>=24.0.0',
			},
		},
	},
	{
		files: ['test/vue/src/*.ts'],
		rules: {
			'require-unicode-regexp': 0,
			'regexp/prefer-regexp-exec': 0,
			'n/no-extraneous-import': [
				2,
				{
					allowModules: [
						'@typescript-eslint/parser',
						'eslint',
						'semver',
						'typescript',
						'vue-eslint-parser',
					],
				},
			],
			'n/no-missing-import': 0,
			'n/no-unpublished-import': 0,
			'@typescript-eslint/await-thenable': 0,
			'@typescript-eslint/explicit-function-return-type': 0,
			'@typescript-eslint/no-shadow': 0,
			'@typescript-eslint/no-unnecessary-boolean-literal-compare': 0,
			'@typescript-eslint/no-unnecessary-condition': 0,
			'@typescript-eslint/no-unnecessary-type-assertion': 0,
			'@typescript-eslint/no-unsafe-argument': 0,
			'@typescript-eslint/no-unsafe-member-access': 0,
			'@typescript-eslint/no-unused-vars': 0,
			'@typescript-eslint/no-useless-default-assignment': 0,
			'@typescript-eslint/prefer-destructuring': 0,
			'@typescript-eslint/prefer-string-starts-ends-with': 0,
		},
	},
	{
		files: ['test/migrate/**/*.js'],
		rules: {
			strict: 0,
		},
	},
	{
		files: ['shim/*.js'],
		rules: {
			'class-methods-use-this': 0,
			strict: [
				2,
				'never',
			],
			'n/exports-style': 0,
		},
	},
);
